config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get '/organizations', to: 'organizations#index'

  put '/set_driver_and_vehicle', to: 'organizations#set_driver_and_vehicle'

  root to: 'organizations#index'

end

app/models/organization.rb
class Organization < ApplicationRecord
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_params, only: :set_driver_and_vehicle
  
  def index
     @routes = Route.all.order(:id)
     @drivers = Driver.where(organization: current_user.organization)
     @vehicles = Vehicle.where(organization: current_user.organization)
     set_timeline
     set_timeline_painted
  end

  def set_driver_and_vehicle
    return redirect_to(organizations_path, alert: 'Error: Conductor con tope de horario') unless @route.can_assing_driver?(@driver)
    return redirect_to(organizations_path, alert: 'Error: Vehículo con tope de horario') unless @route.can_assing_vehicle?(@vehicle)
    
    @route.update(vehicle_id: @vehicle.id, driver_id: @driver.id)
    redirect_to(organizations_path, alert: 'Asignacion exitosa')
  end

  def set_params
    @route = Route.find(params[:route_id])
    @vehicle = Vehicle.find(params[:vehicle_id])
    @driver = Driver.find(params[:driver_id])
  end

  def set_timeline
    @time_hours = []
    init_of_day = Time.zone.today + 9.hours
    end_of_day = Time.zone.today + 18.hours
    while init_of_day <= end_of_day
      @time_hours << init_of_day.strftime("%H:%M")
      init_of_day = init_of_day + 15.minutes
    end
    @time_hours
  end

  def set_timeline_painted
    day = Route.last.starts_at.beginning_of_day #set for example on the day of defined routes
    @time_hours_painted = [] 
    init_of_day = day + 9.hours
    end_of_day = day + 18.hours
    while init_of_day <= end_of_day
      @time_hours_painted << { time: init_of_day, hour: init_of_day.strftime("%H:%M") }
      init_of_day = init_of_day + 10.minutes
    end
    @time_hours_painted
  end
end

app/views/organizations/index.slim
.row.mx-3.py-5
  .col-8
	  h1 Conjunto de rutas
  .col-2 
    p Usuario #{current_user.email}
    p Organizacion #{current_user.organization.name}
  .col-2
    a.px-5  = link_to destroy_user_session_path, :method => :delete, html: {'data-turbo' => "false"}
      span.btn.btn-secondary.justify-content-end logout
.row 
  .col-6.px-4
    p Total de rutas #{@routes.count}
.row 
	.col-8.px-4
			table.table.table-responsive
				thead.background-header
					tr 
						th Nombre 
						th Fecha
						th Hora 
						th Tiempo 
						th Paradas 
						th Accion 
						th Vehiculo
						th Conductor
						th Accion
				tbody 
					- @routes.each do |r|
						=form_with(url: set_driver_and_vehicle_path , method: "put", html: { class: 'form', 'data-turbo'=> 'false'}) do |f|
							= f.hidden_field :route_id, value: r.id
							tr  
								td = r.name 
								th = r.date
								td = "#{r.starts_at_hour} hasta #{r.ends_at_hour}"
								td = r.hours_duration
								td = '0'
								td = 'Llegada'
								td = f.select :vehicle_id, options_from_collection_for_select(@vehicles, 'id', 'plate', selected: r.vehicle&.id)
								td = f.select :driver_id, options_from_collection_for_select(@drivers, 'id', 'name', selected: r.driver&.id)
								td = f.submit 'asignar', class:'btn btn-primary'
    .col-3.px-2
      = image_tag("maps.png", class: "image-root ms-3", data: { target: "image-preview.output" })
.row
    .col-11.d-flex.ml-auto
      - @time_hours.each do |t|
        div.time_line_size.hour-text | #{t}
- @routes.each do |r|
  .row
    .col-1.max-height
      p.h-50.my-0.bold #{r.name}
      p.h-50.my-0 #{r.vehicle&.plate.nil? ? "Sin asignar" : "#{r.vehicle&.plate}/#{r.driver&.name}"}
    .col-11.d-flex.max-height.py-2
      - @time_hours_painted.each do |t|
        - if (t[:time].in_time_zone).between?(r.starts_at, r.ends_at-10.minutes)
          div.color-time
        - else
          - unless r.another_routes_by_assigned.count.zero?
            - r.another_routes_by_assigned.each do |rd|
              - if (t[:time].in_time_zone).between?(rd.starts_at, rd.ends_at)
                div.color-time-assigned
              - else
                div.without-color-time
          - else
            div.without-color-time
.row
  